apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  db-user: YWRtaW4=  # Base64-encoded value of "admin"
  db-password: MWYyZDFlMmU2N2Rm==  # Base64-encoded value of "1f2d1e2e67df"
