apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: my-app
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
